# Platform.sh deployment configuration
name: berlin-hamburg-corridor-analysis
type: nodejs:18

variables:
  env:
    NODE_ENV: production

dependencies:
  nodejs:
    npm: "*"

hooks:
  build: |
    npm install
    npm run build
  deploy: |
    echo "Deployment completed"

web:
  commands:
    start: npm start
  locations:
    "/":
      root: "dist"
      index: ["index.html"]
      expires: 1y
      scripts: false
      allow: true
      rules:
        # Handle API routes
        '^/api/':
          passthru: true
        # Handle static assets
        '\.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$':
          allow: true
        # Fallback to index.html for SPA routing
        '^/':
          try_files: ["$uri", "/index.html"]

disk: 1024

mounts:
  "tmp":
    source: local
    source_path: tmp

runtime:
  extensions:
    - redis

relationships: {}